# Generated by Django 4.1.2 on 2022-11-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_product', models.ImageField(upload_to='product/')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.SlugField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
