# Generated by Django 3.2.16 on 2022-12-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_referentes_swbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referentes_desarrollo',
            name='imagen_area_home',
        ),
        migrations.RemoveField(
            model_name='referentes_desarrollo',
            name='nombres_home',
        ),
        migrations.RemoveField(
            model_name='referentes_soporte',
            name='imagen_area_home',
        ),
        migrations.RemoveField(
            model_name='referentes_soporte',
            name='nombres_home',
        ),
        migrations.RemoveField(
            model_name='referentes_swbase',
            name='imagen_area_home',
        ),
        migrations.RemoveField(
            model_name='referentes_swbase',
            name='nombres_home',
        ),
    ]
