# Generated by Django 3.2.16 on 2022-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20221217_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentes_desarrollo',
            name='imagen_error_desarrollo',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_desa/'),
        ),
        migrations.AlterField(
            model_name='referentes_soporte',
            name='imagen_error_soporte',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_desa/'),
        ),
        migrations.AlterField(
            model_name='referentes_swbase',
            name='imagen_error_swbase',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_desa/'),
        ),
    ]
