# Generated by Django 3.2.16 on 2022-12-18 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20221218_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagen_errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_error', models.ImageField(blank=True, null=True, upload_to='Referentes_desa/')),
            ],
        ),
        migrations.AlterField(
            model_name='referentes_soporte',
            name='imagen_error_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.imagen_errores'),
        ),
    ]
