# Generated by Django 3.2.16 on 2022-12-19 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20221218_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_errores_soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='referentes_soporte',
            name='imagen_error_soporte',
        ),
        migrations.DeleteModel(
            name='imagen_errores',
        ),
        migrations.AddField(
            model_name='imagen_errores_soporte',
            name='imagen_error_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.referentes_soporte'),
        ),
    ]
