# Generated by Django 3.2.16 on 2022-12-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20221218_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referentes_soporteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
