# Generated by Django 3.2.16 on 2022-12-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_delete_referentes_soporteadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referentes_desarrollo',
            old_name='imagen_error_desarrollo',
            new_name='imagen_error_desarrollodos',
        ),
        migrations.RemoveField(
            model_name='referentes_swbase',
            name='imagen_error_swbase',
        ),
        migrations.AddField(
            model_name='referentes_desarrollo',
            name='imagen_error_desarrollotres',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_desa/'),
        ),
        migrations.AddField(
            model_name='referentes_desarrollo',
            name='imagen_error_desarrollouno',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_desa/'),
        ),
        migrations.AddField(
            model_name='referentes_soporte',
            name='imagen_error_desarrollodos',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_soporte/'),
        ),
        migrations.AddField(
            model_name='referentes_soporte',
            name='imagen_error_desarrollotres',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_soporte/'),
        ),
        migrations.AddField(
            model_name='referentes_soporte',
            name='imagen_error_desarrollouno',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_soporte/'),
        ),
        migrations.AddField(
            model_name='referentes_swbase',
            name='imagen_error_swbasedos',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_swbase/'),
        ),
        migrations.AddField(
            model_name='referentes_swbase',
            name='imagen_error_swbasetres',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_swbase/'),
        ),
        migrations.AddField(
            model_name='referentes_swbase',
            name='imagen_error_swbaseuno',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_swbase/'),
        ),
        migrations.DeleteModel(
            name='Imagen_errores_soporte',
        ),
    ]
