# Generated by Django 3.2.16 on 2022-12-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20221218_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referentes_soporte',
            old_name='imagen_error_desarrollodos',
            new_name='imagen_error_soporteuno',
        ),
        migrations.RemoveField(
            model_name='referentes_soporte',
            name='imagen_error_desarrollotres',
        ),
        migrations.RemoveField(
            model_name='referentes_soporte',
            name='imagen_error_desarrollouno',
        ),
    ]
