# Generated by Django 3.2.16 on 2022-12-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20221218_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentes_soporte',
            name='imagen_error_soportedos',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_soporte/'),
        ),
        migrations.AddField(
            model_name='referentes_soporte',
            name='imagen_error_soportetres',
            field=models.ImageField(blank=True, null=True, upload_to='Referentes_soporte/'),
        ),
    ]
