# Generated by Django 3.2.16 on 2022-12-21 21:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_referentes_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentes_soporte',
            name='imagen_error_soportedos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_soporte',
            name='imagen_error_soportetres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_soporte',
            name='imagen_error_soporteuno',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
