# Generated by Django 3.2.16 on 2022-12-23 18:15

import ckeditor.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0016_auto_20221221_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentes_desarrollo',
            name='imagen_error_desarrollodos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_desarrollo',
            name='imagen_error_desarrollotres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_desarrollo',
            name='imagen_error_desarrollouno',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_redes',
            name='imagen_error_redesdos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_redes',
            name='imagen_error_redestres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_redes',
            name='imagen_error_redesuno',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_seginf',
            name='imagen_error_seginfdos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_seginf',
            name='imagen_error_seginftres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_seginf',
            name='imagen_error_seginfuno',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_swbase',
            name='imagen_error_swbasedos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_swbase',
            name='imagen_error_swbasetres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_swbase',
            name='imagen_error_swbaseuno',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_tel',
            name='imagen_error_teldos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_tel',
            name='imagen_error_teltres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referentes_tel',
            name='imagen_error_teluno',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_error_formulariouno', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('imagen_error_formulariodos', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('imagen_error_formulariotres', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('area_principal', models.CharField(max_length=50, null=True)),
                ('nombre_referente', models.CharField(max_length=50, null=True)),
                ('nombres_integrantes', models.CharField(max_length=60, null=True)),
                ('apps', models.CharField(max_length=500, null=True)),
                ('titulo_error', models.CharField(max_length=50, null=True)),
                ('descripcion_error', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha_error', models.DateField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
