# Generated by Django 3.2.16 on 2023-05-28 20:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
