# Generated by Django 3.2.16 on 2023-05-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20230528_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='enlace',
        ),
    ]
